repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
        language_version: python3
  - repo: local
    hooks:
      - id: pipenv-lock
        name: pipenv-lock
        entry: bash -c 'pipenv lock -r > requirements.txt'
        language: system
