[tool.isort]
profile = "black"
force_sort_within_sections = "True"
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
line_length = 88

[tool.black]
fast = "True"

[tool.autopep8]
max_line_length = 88
extend-ignore = ['E203', 'W503']

